### PR TITLE
This version not only corrected the right labels bug but also updated the example

### PR DESCRIPTION
**Pull request by brianpenghe**

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Really nice updated test/example! I'm going to merge this, once the tests are passing. Could you check them, please?

**Comment by brianpenghe** [comment]
> Really nice updated test/example! I'm going to merge this, once the tests are passing. Could you check them, please?

What do you mean by check them? It worked on my computer. I'm not familiar with the travis-ci. Will learn it.

**Comment by Pierre-Sassoulas** [comment]
Sorry it was not very clear. You can launch the tests locally with : `python -m unittest`, you should have the same error than in travis :

```
ERROR: test_no_fail_readme (pysankey.tests.test_readme_fruit.TestReadmeFruit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Pierre-Sassoulas/pySankey/pysankey/tests/test_readme_fruit.py", line 18, in test_no_fail_readme
    figureName=self.figure_name,
  File "/home/travis/build/Pierre-Sassoulas/pySankey/pysankey/sankey.py", line 176, in sankey
    raise ValueError(msg)
ValueError: The colorDict parameter is missing values for the following labels : kiwi
======================================================================
FAIL: test_bad_color_labels (pysankey.tests.test_error_case.TestErrorCase)
sankey raise a value error when there is not enough color info
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Pierre-Sassoulas/pySankey/pysankey/tests/test_error_case.py", line 23, in test_bad_color_labels
    self.assertIn(": blueberry, lime, banana", str(value_error.exception))
AssertionError: ': blueberry, lime, banana' not found in 'The colorDict parameter is missing values for the following labels : lime, blueberry, banana, kiwi'
````

But you can test a lot faster locally :) !

**Comment by brianpenghe** [comment]
I just pushed something to fix that error. But another error occurred when I tested locally:

```
E
======================================================================
ERROR: pysankey (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pysankey
Traceback (most recent call last):
  File "/Users/Brian/anaconda3/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/Users/Brian/anaconda3/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/Brian/Dropbox/scripts/pySankey/pysankey/__init__.py", line 3, in <module>
    from pysankey.sankey import sankey, PySankeyException, NullsInFrame, LabelMismatch
  File "/Users/Brian/Dropbox/scripts/pySankey/pysankey/sankey.py", line 149
    LOGGER.debug(f"Labels to handle : {allLabels}")
                                                 ^
SyntaxError: invalid syntax
```

**Comment by brianpenghe** [comment]
> Sorry it was not very clear. You can launch the tests locally with : `python -m unittest`, you should have the same error than in travis :
> 
> ```
> ERROR: test_no_fail_readme (pysankey.tests.test_readme_fruit.TestReadmeFruit)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/Pierre-Sassoulas/pySankey/pysankey/tests/test_readme_fruit.py", line 18, in test_no_fail_readme
>     figureName=self.figure_name,
>   File "/home/travis/build/Pierre-Sassoulas/pySankey/pysankey/sankey.py", line 176, in sankey
>     raise ValueError(msg)
> ValueError: The colorDict parameter is missing values for the following labels : kiwi
> ======================================================================
> FAIL: test_bad_color_labels (pysankey.tests.test_error_case.TestErrorCase)
> sankey raise a value error when there is not enough color info
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/Pierre-Sassoulas/pySankey/pysankey/tests/test_error_case.py", line 23, in test_bad_color_labels
>     self.assertIn(": blueberry, lime, banana", str(value_error.exception))
> AssertionError: ': blueberry, lime, banana' not found in 'The colorDict parameter is missing values for the following labels : lime, blueberry, banana, kiwi'
> ```
> 
> But you can test a lot faster locally :) !

And dude can we chat on a more effective app? like whatsapp etc.?

**Comment by Pierre-Sassoulas** [comment]
@brianpenghe I see what the problem is and I'm going to merge and fix it myself.  Thank you for your contribution, really appreciated :)

**Comment by brianpenghe** [comment]
> @brianpenghe I see what the problem is and I'm going to merge and fix it myself. Thank you for your contribution, really appreciated :)

bitmoji
bitmoji

**Pull request merged**
