### PR TITLE
fixed the bug in right labels

### PR DESCRIPTION
**Pull request by brianpenghe**
The test example has identical leftlabel and rightlabel so it can't tell you about this bug

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
@brianpenghe thank you for the PR and nice catch! Could you add your example in the automated tests?

**Comment by brianpenghe** [comment]
> @brianpenghe thank you for the PR and nice catch! Could you add your example in the automated tests?

My table is too big and complicated. I can modify that example to make it work

**Comment by brianpenghe** [comment]
I'll include those changes in the new pull request

**Comment by Pierre-Sassoulas** [comment]
I'll merge the other pull request, but just for the record you can modify a pull request by pushing again and you can also reopen a closed pull request :)

**Pull request closed without merging**
